name: build

on:
  pull_request:
  push:
    branches:
      - master
      - 'releases/*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: ^1.16
    - name: Build executable
      run: go build -buildmode exe -o kojirou kojirou.go
    - name: Upload executable
      uses: actions/upload-artifact@v3
      with:
        name: dist-kojirou-executable
        path: kojirou
