name: build

on:
  pull_request:
  push:
    branches:
      - master
      - 'releases/*'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        GOOS:
          - linux
          - windows
        GOARCH:
          - amd64
          - 386
          - arm64
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: ^1.16
    - name: Build executable
      env:
        GOOS: ${{ matrix.GOOS }}
        GOARCH: ${{ matrix.GOARCH }}
      run: |
        go build -buildmode exe -o kojirou.exe kojirou.go
    - name: Upload executable
      uses: actions/upload-artifact@v3
      with:
        name: dist-kojirou-${{ matrix.GOOS }}/${{ matrix.GOARCH }}
        path: kojirou.exe
